services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_CHAT_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - /mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - chat-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb-volume:/data/db
    networks:
      - chat-network
    command: ["mongod", "--bind_ip_all"]

  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - neo4j-volume:/data
    networks:
      - chat-network

  chat_app:
    container_name: chat_app
    image: chat_app:v1.0
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3001"
    volumes:
      - mysql-dumps:/var/backups/mysql
      - mongodb-dumps:/var/backups/mongodb
      - neo4j-dumps:/var/backups/neo4j
    networks:
      - chat-network
    depends_on:
      - mysql
      - mongodb
      - neo4j

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-volume:
  mysql-dumps:
  mongodb-volume:
  mongodb-dumps:
  neo4j-volume:
  neo4j-dumps:
