services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - /mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - chat-network

  chat_app_backend:
    container_name: chat_app_backend
    image: niiicolaidk/chat-app-backend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - mysql-dumps:/var/backups/mysql
    networks:
      - chat-network
    depends_on:
      - mysql

  chat_client_react:
    container_name: chat_client_react
    image: niiicolaidk/chat-app
    environment:
      - NODE_ENV=development
    ports:
      - "5174:5174"
    depends_on:
      - chat_app_backend

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-volume:
  mysql-dumps:
