services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - /mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - chat-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb-volume:/data/db
    networks:
      - chat-network

  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-volume:/data
    networks:
      - chat-network

  chat_app_backend:
    container_name: chat_app_backend
    image: niiicolaidk/chat-app-backend:latest
    environment:
      - NODE_ENV=production
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - NEO4J_PASSWORD=password
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - mysql-dumps:/var/backups/mysql
      - mongodb-dumps:/var/backups/mongodb
      - neo4j-dumps:/var/backups/neo4j
    networks:
      - chat-network
    command: ["sh", "./wait_for_start.sh", "--db-overwrite"]
    depends_on:
      - mysql
      - mongodb
      - neo4j

  chat_client_react:
    container_name: chat_client_react
    image: niiicolaidk/chat-app
    environment:
      - NODE_ENV=production
    ports:
      - "5174:5174"
    depends_on:
      - chat_app_backend

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-volume:
  mysql-dumps:
  mongodb-volume:
  mongodb-dumps:
  neo4j-volume:
  neo4j-dumps:
