services:
  chat_app:
    container_name: chat_app
    image: chat_app:v1.0
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - mysql-dumps:/var/backups/mysql
    networks:
      - chat-network

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_CHAT_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - /mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-volume:
  mysql-dumps:
