services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_CHAT_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - /mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - chat-network

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/data/db
    networks:
      - chat-network

  chat_app:
    container_name: chat_app
    image: chat_app:v1.0
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - mysql-dumps:/var/backups/mysql
    networks:
      - chat-network
    depends_on:
      - mysql
      - mongodb

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-volume:
  mysql-dumps:
  mongodb-volume:
