services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - /mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - chat-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb-volume:/data/db
    networks:
      - chat-network

  chat_app_backend:
    container_name: chat_app_backend
    image: niiicolaidk/chat-app-backend:latest
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - mysql-dumps:/var/backups/mysql
    networks:
      - chat-network
    command: ["sh", "-c", "./wait-for-it.sh mysql:3306 -- npm run db:override && npm start"]
    depends_on:
      - mysql
      - mongodb

  chat_client_react:
    container_name: chat_client_react
    image: niiicolaidk/chat-app
    environment:
      - NODE_ENV=production
    ports:
      - "5174:5174"
    depends_on:
      - chat_app_backend

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-volume:
  mysql-dumps:
  mongodb-volume:
