export default {
    eq: '=',
    ne: '!=',
    gt: '>',
    gte: '>=',
    lt: '<',
    lte: '<=',
    like: 'LIKE',
    notLike: 'NOT LIKE',
    in: 'IN',
    notIn: 'NOT IN',
    between: 'BETWEEN',
    notBetween: 'NOT BETWEEN',
    is: 'IS',
    isNot: 'IS NOT',
    notNull: 'IS NOT NULL',
    isNull: 'IS NULL',
    regexp: 'REGEXP',
    notRegexp: 'NOT REGEXP',
    iLike: 'ILIKE',
    notILike: 'NOT ILIKE',
}
